trigger:
- refs/pulls/5

pr: 
- main

extends:
  template: template.yml
  parameters:
    stages:
    - stage: stage1
      displayName: Stage 1
      jobs:
      - job: job1_1
        displayName: Stage 1, job1.1
        steps:
        - script: echo "my secret is $(my_secret)"
        - script: echo "Im job 1.1"
